name = "TransmissionChannelAnalysis"
uuid = "d500094b-e8d7-4ee4-9514-4e3996dd73c3"
authors = ["Enrico Wegner"]
version = "2.0.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Combinatorics = "1.0"
julia = "1.7"

[extras]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Serialization", "JSON"]
