name = "TransmissionMechanisms"
uuid = "d500094b-e8d7-4ee4-9514-4e3996dd73c3"
authors = ["Enrico Wegner"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
