name = "TransmissionMechanisms"
uuid = "d500094b-e8d7-4ee4-9514-4e3996dd73c3"
authors = ["Enrico Wegner"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
SymbolicUtils = "1.4"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[targets]
test = ["Test", "Serialization"]
